import {
  BookOpen,
  ChartNoAxesCombined,
  FlaskConical,
  Funnel,
  ListChecks,
  Plug,
  Settings2,
  Users,
  FileChartColumn,
  CalendarDays,
} from "lucide-react";
export const navigation = [
  {
    href: "/today",
    label: "Today",
    group: "Workspace",
    icon: CalendarDays,
    description: "Your daily priorities, follow-ups, and operating rhythm.",
    phase: 3,
  },
  {
    href: "/performance",
    label: "Performance",
    group: "Workspace",
    icon: ChartNoAxesCombined,
    description: "Paid media performance, with context for every metric.",
    phase: 10,
  },
  {
    href: "/leads",
    label: "Leads",
    group: "Workspace",
    icon: Users,
    description: "Every inquiry, its attribution, and the next step.",
    phase: 6,
  },
  {
    href: "/funnel",
    label: "Funnel",
    group: "Workspace",
    icon: Funnel,
    description: "Follow inquiries through qualification and outcomes.",
    phase: 6,
  },
  {
    href: "/experiments",
    label: "Experiments",
    group: "Operations",
    icon: FlaskConical,
    description: "Turn hypotheses into a repeatable learning process.",
    phase: 5,
  },
  {
    href: "/playbook",
    label: "Playbook",
    group: "Operations",
    icon: BookOpen,
    description: "The operating knowledge behind consistent decisions.",
    phase: 4,
  },
  {
    href: "/workflows",
    label: "Workflows",
    group: "Operations",
    icon: ListChecks,
    description: "Reusable checklists for your marketing routine.",
    phase: 3,
  },
  {
    href: "/reports",
    label: "Reports",
    group: "Operations",
    icon: FileChartColumn,
    description: "A clear account of performance, decisions, and learning.",
    phase: 12,
  },
  {
    href: "/integrations",
    label: "Integrations",
    group: "Administration",
    icon: Plug,
    description: "Connection status and data freshness across your sources.",
    phase: 7,
  },
  {
    href: "/settings",
    label: "Settings",
    group: "Administration",
    icon: Settings2,
    description: "Workspace preferences and operating configuration.",
    phase: 2,
  },
] as const;
export function navigationFor(path: string) {
  return navigation.find(
    (item) => path === item.href || path.startsWith(item.href + "/"),
  );
}
